"""create study year table

Revision ID: 264ad6eda588
Revises: 23ffbed229a1
Create Date: 2025-01-10 21:50:51.691397

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '264ad6eda588'
down_revision = '23ffbed229a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('study_year',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('study_year_code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('study_year_code')
    )
    # ### end Alembic commands ###
    op.execute("COMMIT")


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('study_year')
    # ### end Alembic commands ###
    op.execute("COMMIT")

