"""add tests table

Revision ID: cae2660f9e77
Revises: 63088d759daf
Create Date: 2025-01-31 13:47:33.950844

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cae2660f9e77'
down_revision = '63088d759daf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('factor', sa.Integer(), nullable=False),
    sa.Column('semester', sa.Enum('FIRST_SEMESTER', 'SECOND_SEMESTER', name='semesterenum'), nullable=False),
    sa.Column('grade_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['grade_id'], ['grade.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
    op.execute("COMMIT")

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tests')
    # ### end Alembic commands ###
    op.execute("COMMIT")