"""create student unit (student class) table

Revision ID: 2f24d6a93948
Revises: ed77b7c7f47a
Create Date: 2025-01-10 22:13:08.448764

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f24d6a93948'
down_revision = 'ed77b7c7f47a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student_unit',
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('unit_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], ),
    sa.ForeignKeyConstraint(['unit_id'], ['unit.id'], ),
    sa.PrimaryKeyConstraint('student_id', 'unit_id')
    )
    # ### end Alembic commands ###
    op.execute("COMMIT")

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('student_unit')
    # ### end Alembic commands ###
    op.execute("COMMIT")
