"""create unit (class) table

Revision ID: ed77b7c7f47a
Revises: 466f55350960
Create Date: 2025-01-10 22:07:13.159151

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed77b7c7f47a'
down_revision = '466f55350960'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('unit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('unit_id', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('grade_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['grade_id'], ['grade.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('unit_id')
    )
    # ### end Alembic commands ###
    op.execute("COMMIT")

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('unit')
    # ### end Alembic commands ###
    op.execute("COMMIT")
