"""create grade table

Revision ID: 466f55350960
Revises: 264ad6eda588
Create Date: 2025-01-10 21:55:21.225645

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '466f55350960'
down_revision = '264ad6eda588'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('grade',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('grade_code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('study_year_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['study_year_id'], ['study_year.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('grade_code')
    )
    # ### end Alembic commands ###
    op.execute("COMMIT")


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('grade')
    # ### end Alembic commands ###
    op.execute("COMMIT")

