"""add attendance table

Revision ID: 63088d759daf
Revises: 2f24d6a93948
Create Date: 2025-01-25 15:26:58.247006

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63088d759daf'
down_revision = '2f24d6a93948'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student_attendance',
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('attendance_date', sa.Date(), nullable=False),
    sa.Column('mass_status', sa.Enum('PRESENT', 'NOTIFIED_ABSENT', 'ABSENT', name='attendancestatusenum'), nullable=True),
    sa.Column('lesson_status', sa.Enum('PRESENT', 'NOTIFIED_ABSENT', 'ABSENT', name='attendancestatusenum'), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], ),
    sa.PrimaryKeyConstraint('student_id', 'attendance_date')
    )
    # ### end Alembic commands ###
    op.execute("COMMIT")

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('student_attendance')
    # ### end Alembic commands ###
    op.execute("COMMIT")
